backend:
  name: git-gateway
  branch: master
  # branch: develop # Branch to update (optional; defaults to master)
# local_backend: true
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "project" # Used in routes, e.g., /admin/collections/blog
    label: "Project" # Used in the UI
    folder: "_content/posts/project" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    media_folder: '/static/images/uploads'
    public_folder: '../../../static/images/uploads'
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "experiment" # Used in routes, e.g., /admin/collections/blog
    label: "Experiment" # Used in the UI
    folder: "_content/posts/experiment" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    media_folder: '/static/images/uploads'
    public_folder: '../../../static/images/uploads'
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "website" # Used in routes, e.g., /admin/collections/blog
    label: "Website" # Used in the UI
    folder: "_content/posts/website" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    media_folder: '/static/images/uploads'
    public_folder: '../../../static/images/uploads'
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
        - label: "About"
          name: "about"
          file: "_content/pages/about.md"
          fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: body, widget: markdown }
              - label: "Jobs"
                name: "jobs"
                widget: "list"
                fields:
                    - { label: Where, name: where, widget: string}
                    - { label: Years, name: years, widget: string }
                    - { label: Role, name: role, widget: string }
                    - { label: Description, name: description, widget: string }
              - label: "Education"
                name: "education"
                widget: "list"
                fields:
                    - { label: Where, name: where, widget: string}
                    - { label: Years, name: years, widget: string }
                    - { label: Role, name: role, widget: string }
            
              